# Generated by Django 6.1.1 on 2026-09-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='therapist_avatars/'),
        ),
    ]
