# Generated by Django 6.1.1 on 2026-09-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_alter_scheduleslot_options_and_more'),
        ('session_management', '0002_session_cancellation_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='schedule_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='schedules.scheduleslot'),
        ),
    ]
