# Generated by Django 6.1.1 on 2026-09-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.CharField(choices=[('patient', 'Patient Issue'), ('booking', 'Booking Issue'), ('payment', 'Payment Issue'), ('technical', 'Technical Issue'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
