# Generated by Django 6.1.1 on 2026-09-16 07:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleslot',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RemoveConstraint(
            model_name='scheduleslot',
            name='unique_therapist_schedule_slot',
        ),
        migrations.RenameField(
            model_name='scheduleslot',
            old_name='end_time',
            new_name='time',
        ),
        migrations.AddConstraint(
            model_name='scheduleslot',
            constraint=models.UniqueConstraint(fields=('therapist', 'date', 'time'), name='unique_therapist_schedule_slot'),
        ),
        migrations.RemoveField(
            model_name='scheduleslot',
            name='start_time',
        ),
    ]
